// src/utils/pdfTemplate.js
export const resumeTemplate = (data) => {
  const skillsHtml = (data.skills || []).map(s => `<li>${s}</li>`).join("");
  const expHtml = (data.experience || []).map(e => `
    <div style="margin-bottom:10px;">
      <strong>${e.role} — ${e.company}</strong><br/>
      <small>${e.duration}</small>
      <p style="margin:6px 0;">${e.desc}</p>
    </div>
  `).join("");

  const educationHtml = (data.education || []).map(ed => `
    <div style="margin-bottom:8px;">
      <strong>${ed.degree} — ${ed.school}</strong>
      <p style="margin:6px 0;">${ed.year} | ${ed.result || ""}</p>
    </div>
  `).join("");

  return `
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8"/>
      <meta name="viewport" content="width=device-width,initial-scale=1" />
    </head>
    <body style="font-family: Arial; color: #111; padding: 20px;">
      <div style="display:flex; justify-content:space-between; align-items:center; border-bottom:2px solid #eee; padding-bottom:10px;">
        <div>
          <h1 style="margin:0;">${data.name || ""}</h1>
          <div style="color:#444;">${data.title || ""}</div>
        </div>
        <div style="text-align:right;">
          <div>${data.email || ""}</div>
          <div>${data.phone || ""}</div>
          <div>${data.address || ""}</div>
        </div>
      </div>

      <div style="margin-top:18px;">
        <h3 style="margin-bottom:6px;">Summary</h3>
        <p style="margin-top:0;">${data.summary || ""}</p>
      </div>

      <div style="display:flex; gap:12px;">
        <div style="width:60%; float:left;">
          <h3>Experience</h3>
          ${expHtml || "<p>No experience added.</p>"}
        </div>
        <div style="width:35%; float:right;">
          <h3>Skills</h3>
          <ul>${skillsHtml}</ul>

          <h3>Education</h3>
          ${educationHtml || "<p>No education added.</p>"}
        </div>
      </div>

      <div style="clear:both;"></div>
      <div style="margin-top:18px; color:#666; font-size:12px;">Generated by ResumeApp</div>
    </body>
  </html>
  `;
};
